# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffah < Formula
  desc "CLI for layer-level diffs between OCI / Docker container images."
  homepage "https://github.com/leosocy/diffah"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leosocy/diffah/releases/download/v0.2.0/diffah_0.2.0_darwin_amd64.zip"
      sha256 "1df96dc0c81191b414d8a27f5acc496c9c6106b98821672eceb03219dca954ff"

      define_method(:install) do
        bin.install "diffah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leosocy/diffah/releases/download/v0.2.0/diffah_0.2.0_darwin_arm64.zip"
      sha256 "e02ffb9c5895fc9882de0792d026daa4cf2290e0558bedf4cd320f9fb5ff3d26"

      define_method(:install) do
        bin.install "diffah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leosocy/diffah/releases/download/v0.2.0/diffah_0.2.0_linux_amd64.tar.gz"
      sha256 "2cbb57ef62cf4b5c25024f417ec5769a412b5c9b24bae04fb0615cca21b26f28"
      define_method(:install) do
        bin.install "diffah"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leosocy/diffah/releases/download/v0.2.0/diffah_0.2.0_linux_arm64.tar.gz"
      sha256 "d4f56067a3c82bc526982d1694a577b3c67990033afd7e6ab2844c0e32b200f4"
      define_method(:install) do
        bin.install "diffah"
      end
    end
  end

  def caveats
    <<~EOS
      `diffah` works out of the box for archives produced with
      --intra-layer=off (the default). Some intra-layer modes also
      need `zstd` >= 1.5 on $PATH:
        brew install zstd
      Run `diffah doctor` to verify your local environment.
    EOS
  end

  test do
    assert_match "diffah", shell_output("#{bin}/diffah version")
  end
end
